// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Uac2AudioFormat`, `Uac2DeviceCapabilities`, `Uac2ErrorCode`, `Uac2HotplugEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

bool uac2IsAvailable() => RustLib.instance.api.crateApiUac2ApiUac2IsAvailable();

List<Uac2DeviceInfo> uac2ListDevices() =>
    RustLib.instance.api.crateApiUac2ApiUac2ListDevices();

Future<void> uac2Disconnect() =>
    RustLib.instance.api.crateApiUac2ApiUac2Disconnect();

Future<void> uac2SetVolume({required double volume}) =>
    RustLib.instance.api.crateApiUac2ApiUac2SetVolume(volume: volume);

double uac2GetVolume() => RustLib.instance.api.crateApiUac2ApiUac2GetVolume();

Future<void> uac2SetMute({required bool muted}) =>
    RustLib.instance.api.crateApiUac2ApiUac2SetMute(muted: muted);

bool uac2GetMute() => RustLib.instance.api.crateApiUac2ApiUac2GetMute();

Future<Uac2VolumeRange> uac2GetVolumeRange() =>
    RustLib.instance.api.crateApiUac2ApiUac2GetVolumeRange();

Future<void> uac2SetSamplingFrequency({required int frequency}) => RustLib
    .instance
    .api
    .crateApiUac2ApiUac2SetSamplingFrequency(frequency: frequency);

int uac2GetSamplingFrequency() =>
    RustLib.instance.api.crateApiUac2ApiUac2GetSamplingFrequency();

Uac2ConnectionState uac2GetConnectionState() =>
    RustLib.instance.api.crateApiUac2ApiUac2GetConnectionState();

Future<void> uac2SetAutoReconnect({required bool enabled}) =>
    RustLib.instance.api.crateApiUac2ApiUac2SetAutoReconnect(enabled: enabled);

Future<bool> uac2AttemptReconnect() =>
    RustLib.instance.api.crateApiUac2ApiUac2AttemptReconnect();

Uac2FallbackInfo uac2GetFallbackInfo() =>
    RustLib.instance.api.crateApiUac2ApiUac2GetFallbackInfo();

Future<bool> uac2ActivateFallback() =>
    RustLib.instance.api.crateApiUac2ApiUac2ActivateFallback();

Future<void> uac2DeactivateFallback() =>
    RustLib.instance.api.crateApiUac2ApiUac2DeactivateFallback();

class Uac2ConnectionState {
  final String state;
  final int reconnectAttempts;
  final bool autoReconnectEnabled;

  const Uac2ConnectionState({
    required this.state,
    required this.reconnectAttempts,
    required this.autoReconnectEnabled,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      reconnectAttempts.hashCode ^
      autoReconnectEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2ConnectionState &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          reconnectAttempts == other.reconnectAttempts &&
          autoReconnectEnabled == other.autoReconnectEnabled;
}

class Uac2DeviceInfo {
  final int vendorId;
  final int productId;
  final String? serial;
  final String productName;
  final String manufacturer;
  final String? deviceName;

  const Uac2DeviceInfo({
    required this.vendorId,
    required this.productId,
    this.serial,
    required this.productName,
    required this.manufacturer,
    this.deviceName,
  });

  @override
  int get hashCode =>
      vendorId.hashCode ^
      productId.hashCode ^
      serial.hashCode ^
      productName.hashCode ^
      manufacturer.hashCode ^
      deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2DeviceInfo &&
          runtimeType == other.runtimeType &&
          vendorId == other.vendorId &&
          productId == other.productId &&
          serial == other.serial &&
          productName == other.productName &&
          manufacturer == other.manufacturer &&
          deviceName == other.deviceName;
}

class Uac2FallbackInfo {
  final bool hasActiveFallback;
  final String? fallbackName;

  const Uac2FallbackInfo({required this.hasActiveFallback, this.fallbackName});

  @override
  int get hashCode => hasActiveFallback.hashCode ^ fallbackName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2FallbackInfo &&
          runtimeType == other.runtimeType &&
          hasActiveFallback == other.hasActiveFallback &&
          fallbackName == other.fallbackName;
}

class Uac2VolumeRange {
  final int min;
  final int max;
  final int resolution;

  const Uac2VolumeRange({
    required this.min,
    required this.max,
    required this.resolution,
  });

  @override
  int get hashCode => min.hashCode ^ max.hashCode ^ resolution.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2VolumeRange &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max &&
          resolution == other.resolution;
}
